#!/bin/sh
[ -f "${fritzConfig:=$HOME/.fritz.config}" ] && . "${fritzConfig}"

fritzIp=${fritzIp:-fritz.box}
fritzUrl=${fritzUrl:-http://${fritzIp}}
fritzSidFile=${fritzSidFile:-"$HOME/.fritz.$fritzIp.sid"}

$(dirname "$0")/fb-ensure-sid || exit 1

(
  curl -s "${fritzUrl}/data.lua?sid=$(cat $fritzSidFile)" -d page=log -d filter=0 | jq ".data.log[]|{date,time,msg}" \
        | iconv -sc -f utf-8 -t ascii \
) | while read -r a b
do
  case $a in
\{)
    Aall=Aall
    ;;
    
\})
    R="${Adate%,} ${Atime%,} ${Amsg}"
    
    if [ "${R%% \[*messages since*\]}" = "$fblog_stopat" ]
    then
      exit 0
    fi
    echo "$R"
    unset $Aall
    ;;
*)
    aa="${a%%:}"
    aa="${aa%%\"}"
    aa="${aa##\"}"
    eval A$aa="$b"
    Aall="$Aall A$aa"
  esac
done |sort | (
  if [ -z "$fb_nodate" ]
  then
    cat
  else
    sed -Ee 's|^[0-9.]* ||'
  fi
)    
