#!/bin/sh
if [ -r $HOME/.fblog-last$SUFFIX ]
then
  export fblog_stopat=`cat $HOME/.fblog-last$SUFFIX`
else
  export fblog_stopat=
fi

$HOME/bin/fb-log | while read line
do
  line="${line% \[FB*\]}"
  echo "$line"
  line="${line%%  \[*messages since*\]}"
  line="${line%% \[*messages since*\]}"
  echo "${line}" > $HOME/.fblog-last$SUFFIX
done
