#!/bin/sh
if [ -r $HOME/.fblog-last$SUFFIX ]
then
  export fblog_stopat=`cat $HOME/.fblog-last$SUFFIX`
else
  export fblog_stopat=
fi

$HOME/bin/fb-log | while read line
do
  line="${line% \[FB*\]}"
  echo "$line"
  if [ "$line" = "${line%% \[*messages since*\]}" ]
  then
    echo "${line%% \[*messages since*\]}" > $HOME/.fblog-last$SUFFIX
  fi
done
